image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - $ chrome --headless --remote-debugging-port=9222 https://chromium.org
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info